root = "."
tmp_dir = "tmp"

[build]
    cmd = "go build -o ./tmp/web ./cmd/web"
    bin = "./tmp/web"
    include_ext = ["go", "html", "css", "js"]
    exclude_dir = ["tmp", "admin", "media", ".git"]
    delay = 1000
