# Generated by Django 6.1 on 2026-09-05 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_strip_photos_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
